### ISSUE TITLE
Ethernet connection not working

### ISSUE THREAD

**Issue by bachejames** [dmarkey/galileo-resurrection#1]
Hi there!!

Thanks SO much for putting together such a comprehensive resource and helping to ensure the future of this tech, incredibly cool!

I am attempting to install the alpine image onto a Galileo Gen 2 (have also tried the arch image but got stuck at the same stage). I have been able to write the image to an SD card, however when I boot the Galileo, I am unable to connect to it via ethernet. Here are the steps I have taken:

1. On an Xubuntu VM, wrote the image to the SD card using the DD command: `sudo dd if=sdcard-alpine.img of=/dev/sda bs=4M conv=fsync status=progress`
2. Booted the SD card. [This is what was logged](https://pastebin.pl/view/6132e97b). As you can see, it is not clear if networking has failed or not, as midway through the boot it logs: 
```
 * Starting networking .../usr/libexec/ifupdown-ng/dhcp: eval: line 1: syntax error: unexpected word (expecting ")")
ifupdown: dependency graph is broken for interface eth0
ifquery: could not validate dependency tree
 * ERROR: networking failed to start
 * ERROR: cannot start chronyd as networking would not start
```
But then later it logs: 
``` * Starting networking ... *   lo ... [ ok ]
 *   eth0 ...udhcpc: started, v1.32.1
```

### Attempting to connect via Ethernet after boot
Connecting the Galileo to a Mac via Ethernet and running `ifconfig` shows that the Ethernet connection is at least active, with an IP address:
```
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 7c:c3:a1:72:8c:df 
	inet6 fe80::c8a:30f9:d8e0:702c%en1 prefixlen 64 secured scopeid 0x7 
	inet 192.168.1.107 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```
Attempting to telnet into the IP address however, fails. ie. running the command `telnet 192.168.1.107` produces the error: `Connection refused. Unable to connect to remote host`

### Attempting to login to the Galileo after boot
At this login prompt, the cursor is flashing as you'd expect, however as soon as I try typing a single character, the cursor kind of freezes by just constantly being visible instead of flashing. I also do not see the character showing at the login prompt as you'd expect as you type something. I am unable to do anything else until I restart, at which point the same thing happens again. Note that I have experienced this issue with every other image I have tried, so it's unlikely to be an issue specific to this image.

So my question is: am I following the correct steps and is the boot log error messages related to Ethernet expected please?

Thanks so much for your help!

**Comment by guidol70** [comment]
I didnt got problems with the Ethernet-Connection and DHCP - did work on the first try ;)
(OK - I didnt get any console-output over the serial port. Has there to be any?)

Also the Login did work without problems :)

Many Thanks for the image!
(would love to see a kernel-version with CIFS-Support for mounting SAMBA-drives)

![Alpine_Linux_on_Intel_Galileo_1stGen](https://user-images.githubusercontent.com/5121124/195793242-bb28c73c-1d16-4285-8012-71a6d5e0ae53.jpg)
